import { StyleSheet } from 'react-native';
import { Colors } from '@constants/colors';

export const filterStyles = StyleSheet.create({
  modalOverlay: { flex: 1, justifyContent: 'flex-end' },
  backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0, 0, 0, 0.7)' },
  bottomSheet: {
    backgroundColor: Colors.bgSecondary,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: Colors.border,
    borderBottomWidth: 0,
    paddingBottom: 20,
    shadowColor: Colors.neonCyan,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 20,
  },
  handleContainer: { alignItems: 'center', paddingVertical: 12 },
  handleBar: { width: 40, height: 4, backgroundColor: Colors.textSubtle, borderRadius: 2 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  title: { color: Colors.neonCyan, fontSize: 18, fontWeight: '800', letterSpacing: 1 },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.bgDark,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.textSubtle,
  },
  closeText: { color: Colors.neonCyan, fontSize: 14, fontWeight: 'bold' },
  content: { paddingHorizontal: 20 },
  sectionTitle: {
    color: Colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1,
    marginBottom: 12,
    marginTop: 8,
  },
  grid2: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 20 },
  grid: { gap: 12, marginBottom: 30 },
  gridRow: { flexDirection: 'row', gap: 12 },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: Colors.bgDark,
    borderWidth: 1,
    borderColor: Colors.textSubtle,
  },
  chip2Col: { flex: 1, minWidth: '45%' },
  chip3Col: { flex: 1 },
  chipActive: { backgroundColor: 'rgba(0, 229, 255, 0.05)', borderColor: Colors.neonCyan },
  dot: { width: 8, height: 8, borderRadius: 4, marginRight: 8 },
  chipText: { color: Colors.textLight, fontSize: 13, fontWeight: '700', letterSpacing: 0.5 },
  chipTextActive: { color: Colors.neonCyan },
  footer: { paddingHorizontal: 20, gap: 12 },
  applyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.neonCyan,
    borderRadius: 12,
    paddingVertical: 16,
    shadowColor: Colors.neonCyan,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 4,
  },
  checkCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: Colors.black,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  checkIcon: { color: Colors.neonCyan, fontSize: 12, fontWeight: '900' },
  applyText: { color: Colors.black, fontSize: 15, fontWeight: '800', letterSpacing: 0.5 },
  resetButton: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    borderRadius: 12,
    backgroundColor: Colors.bgSecondary,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  resetText: { color: Colors.neonCyan, fontSize: 14, fontWeight: '700', letterSpacing: 0.5 },
});
